import { z } from 'zod';
import { addressSchema } from './geography';

export const propertyFormSchema = z.object({
  name: z.string().min(1, 'El nombre es requerido'),
  description: z.string().min(1, 'La descripción es requerida'),
  propertyType: z.string().min(1, 'El tipo de propiedad es requerido'),
  registryNumber: z.string().min(1, 'El número de registro es requerido'),
  functionalUnit: z.string().optional(),
  ownerIntention: z.string().min(1, 'La intención es requerida'),
  commercialStatus: z.string().optional(),
  propertyCondition: z.string().min(1, 'La condición es requerida'),
  thumbnail: z.instanceof(File).optional(),
  images: z.array(z.instanceof(File)).optional(),
  documents: z.array(z.instanceof(File)).optional(),
  coveredMeters: z.string().optional(),
  uncoveredMeters: z.string().optional(),
  rooms: z.string().optional(),
  bathrooms: z.string().min(1, 'La cantidad de baños es requerida'),
  yearOfConstruction: z.string().optional(),
  electricityIdentifier: z.string().optional(),
  gasIdentifier: z.string().optional(),
  ABLIdentifier: z.string().optional(),
  administration: z.string().optional(),
  administrationPhone: z.string().optional(),
  administrationEmail: z.string().optional(),
  administrationAddress: z.string().optional(),
  ownerName: z.string().optional(),
  ownerPhone: z.string().optional(),
  ownerCBU: z.string().optional(),
  ownerAlias: z.string().optional(),
  hasExpenses: z.boolean().optional(),
  hasExtraordinaryExpenses: z.boolean().optional(),
  hasKitchen: z.boolean().optional(),
  hasPatio: z.boolean().optional(),
  hasBarbecue: z.boolean().optional(),
  hasTerrace: z.boolean().optional(),
  hasPool: z.boolean().optional(),
  hasGarden: z.boolean().optional(),
  hasBalcony: z.boolean().optional(),
  hasFurnished: z.boolean().optional(),
  servicesComment: z.string().optional(),
  hasZoom: z.boolean().optional(),
  hasParking: z.boolean().optional(),
  address: addressSchema,
});
